spring.application.name=ActivityServices

server.port = 8082
spring.mongodb.uri=mongodb://localhost:27017/aiactivityfitness
spring.devtools.restart.enabled=false

eureka.client.serviceUrl.defaultZone = http://localhost:8083/eureka/